export const CREATE_CONTACT = "CREATE_CONTACT";
export const GET_CONTACT = "GET_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const CREATE_USER = "CREATE_CONTACT";
export const LOAD_USER = "LOAD_CONTACT";
export const SIGNIN_USER = "CREATE_CONTACT";
export const SIGNOUT_USER = "CREATE_CONTACT";
